---
title: "Gov 50 Final Project"
author: "Emma Rogers"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(infer)
```

```{r}
cars <- read_csv("CAR DETAILS FROM CAR DEKHO.csv")
cars <- cars |>
  filter(fuel %in% c("Diesel", "Petrol")) |>
  mutate(age = 2020 - year)
```

```{r}
cars |>
  ggplot(mapping = aes(x = selling_price)) +
  geom_histogram(color = "black", fill = "darkslategray1") +
  labs(x = "Price of Used Car (in dollars)",
       y = "Number of Cars Sold",
       title = "Selling Prices of Used Cars") +
  geom_vline(aes(xintercept = mean(selling_price)), color = "indianred") +
  geom_vline(aes(xintercept = median(selling_price)), color = "blue1") +
  theme_classic() 
```
```{r}
cars |>
  ggplot(mapping = aes(x = selling_price)) +
  geom_histogram(color = "black", fill = "darkslategray1") +
  labs(x = "Price of Used Car (in dollars)",
       y = "Number of Cars Sold",
       title = "Selling Prices of Used Cars") +
  geom_vline(aes(xintercept = mean(selling_price)), color = "indianred") +
  geom_vline(aes(xintercept = median(selling_price)), color = "blue1") +
  theme_classic() +
  facet_wrap(~ fuel)
```


```{r}
library(broom)

fit_price <- lm(selling_price ~ km_driven, data = cars)
fit_price
glance(fit_price)

mult_fit <- lm(selling_price ~ km_driven + fuel, data = cars)
mult_fit
glance(mult_fit)

cars |>
  ggplot(mapping = aes(x = km_driven, y = selling_price)) +
  geom_point(alpha = 0.5) +
  ylim(0, 10000000) +
  geom_smooth(method = "lm", se = FALSE) +
  labs(x = "Distance Traveled by Car (in Kilometers)",
       y = "Price of Car",
       title = "Relationship between distance traveled by car and selling price")

```

```{r}
## remove outliers
cars_edit <- cars |>
  filter(km_driven < 5e+05 & selling_price < 7500000)
edit_fit <-
  lm(selling_price ~ km_driven, data = cars_edit)
edit_fit
cars_edit |>
  ggplot(mapping = aes(x = km_driven, y = selling_price)) +
  geom_point(alpha = 0.5) +
  geom_smooth(method = "lm", se = FALSE)
  labs(x = "Distance Traveled by Car (in Kilometers)",
       y = "Price of Car",
       title = "Relationship between distance traveled by car and selling price")
```

```{r}
mult_fit2 <- lm(selling_price ~ km_driven + fuel + age, data = cars)
mult_fit2
glance(mult_fit2)
```

```{r}
fit_age <- lm(selling_price ~ age, data = cars)
fit_age
glance(fit_age)
```



```{r}
cars |>
  ggplot(mapping = aes(x = age, y = selling_price)) +
  geom_point(alpha = 0.5) +
  geom_smooth(method = "lm", se = FALSE) +
  labs(x = "Years since car was purchased",
       y = "Price of Car",
       title = "Relationship between car age and selling price")
```



